### ISSUE TITLE
create a demo and review simpspector

### ISSUE THREAD

**Issue by DavidBadura** [simpspector/simpspector#77]
Todo:

* [x] #129 refactor gitlab request handler
* [x] #42 add github support
* [x] #39 input sanitation of `files` config variables

**Comment by DavidBadura** [comment]
done
